users:
  upcoming_event: 5
colors: ["#AC725E",  "#D06B64", "#F83A22", "#FA573C", "#FF7537", "#FFAD46",
  "#42D692", "#16A765", "#B3DC6C", "#FBE983", "#FAD165", "#92E1C0"]
permissions: ["manage", "make_change", "see_detail", "hide_details"]
permissions_can_make_change: [1, 2]
event:
  format_date: "%Y-%m-%d"
  format_time: "%H:%M"
  format_datetime: "%Y-%m-%d %H:%M"
  repeat_data: ["sun", "mon", "tue", "wed", "thu", "fri", "sat"]
repeat:
  repeat_type:
    daily: "daily"
    weekly: "weekly"
    monthly: "monthly"
    yearly: "yearly"
  repeat_every: 30
